### ISSUE TITLE
helptext to info buttons

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#104]
Tidy `helptext` into info buttons

`<span class="helptext">`

Ensure that the solution is still accessible for screen readers.

**Comment by tbentham** [comment]
This is done on a basic level, though still needs tweaking for smaller screens. Also need to check the screen readers thing.

**Comment by jamesgeddes** [comment]
PR when ready :smile:

**Comment by jamesgeddes** [comment]
@tbentham Is this done? I see you mentioned that #235 resolves this, however, the keyword "resolves #{number}" only works in the description.

**Comment by tbentham** [comment]
Kind of, but not really - I converted the help text to info buttons but there are still issues with popovers going off the edge of the page and also not disappearing after clicking.

I'm currently working on form styling in general, which should include fixing the info buttons.

**Comment by jamesgeddes** [comment]
OK fab. Remember to try and keep PRs small wherever possible, ideally one PR per issue.
