### ISSUE TITLE
Make initial registration page centralised

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#108]
Make our initial registration form aesthetically appealing and centralised.

**Comment by CarwynNelson** [comment]
Not sure what is meant by centralised, could you elaborate?

**Comment by jamesgeddes** [comment]
Form fields in the middle of the page, like most of these

https://uicookies.com/bootstrap-registration-form/

**Comment by CarwynNelson** [comment]
Ah I see. I wasn't sure if you meant have the form elements centred, or centralise it architecturally.
