### ISSUE TITLE
Automatically configure DNS from Kubernetes services

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#11]
## Background

The test.geek.zone DNS entry is manually configured in Cloudflare against an AWS loadbalancer that is configured in kubernetes config.

It would be nice if the management of this DNS entry could be done in the Kubernetes cluster. This might also make it easier for us to deploy pull request branches to nice domain names in the future.

## Resources

I came across this helm plugin for cloudflare DNS in kubernetes that might be helpful https://github.com/estafette/estafette-cloudflare-dns.

### Impact

High

### Urgency

Now

**Comment by jamesgeddes** [comment]
@giulio-giunta Is this done?

**Comment by giulio-giunta** [comment]
Yes @jamesgeddes, we deployed the external-dns which does what Carwyn suggested there.

**Comment by jamesgeddes** [comment]
![image](https://user-images.githubusercontent.com/14872636/203431234-498df6b0-56ef-4bec-b0aa-9c3e7d278361.png)
