### ISSUE TITLE
Setup SSL for test.geek.zone

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#12]
## Background

The current deployment of `test.geek.zone` introduced in #10 is only setup for HTTP. We should configure `test.geek.zone` to use HTTPS instead.

This might require using something other than a `LoadBalancer` service in Kubernetes. Setting this up fairly early on in the development cycle will make this process easier when we go to production with membership management.

**Comment by jamesgeddes** [comment]
Assigning to you but it's dangerous to go alone! Take this help from @giulio-giunta @Freshrojek and me!

**Comment by SamWinterhalder** [comment]
@giulio-giunta

**Comment by giulio-giunta** [comment]
SSL has already been implemented on test.geek.zone, but once we switch to join.geek.zone the same configuration will apply seamlessly.
TLS terminates at the load balancer.
