### ISSUE TITLE
Handle declined payments

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#124]
Gracefully handle non payment

**Comment by CarwynNelson** [comment]
I've assigned this to myself as this is something i've been meaning to look at in the payments code for a little while now.

**Comment by SamWinterhalder** [comment]
Currently dealing with some family issues but should be back on this by Jan 1st

**Comment by SamWinterhalder** [comment]
This issue is too broad.
It has been broken down into smaller issues and I have no doubt more will be created being split from this one.
