### ISSUE TITLE
Send email

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#147]
Enable Django to send emails on trigger.

Emails should come from hq@geek.zone using Gmail SMTP

**Comment by jamesgeddes** [comment]
Once again, Django already has this covered https://docs.djangoproject.com/en/3.1/topics/email/

**Comment by jamesgeddes** [comment]
Should use AWS email queue service

**Comment by CarwynNelson** [comment]
> Should use AWS email queue service

To be specific, I mean emails should be queued up instead of sending in the main request flow. The AWS service I was mentioning is AWS SQS (Simple Queue Service) which is a generic queuing service that is not specific to sending emails.

This might help as an explanation https://aws.amazon.com/message-queue/

**Comment by jamesgeddes** [comment]
@CarwynNelson and I have discussed it a bit further and https://docs.celeryproject.org/en/stable/ might be a better solution. I will investigate futher.

**Comment by jamesgeddes** [comment]
@CarwynNelson and I discussed this further and decided to go with https://www.rabbitmq.com/

**Comment by jamesgeddes** [comment]
@CarwynNelson and I need to discuss this further to work out the best implementation method.

**Comment by jamesgeddes** [comment]
https://pypi.org/project/django-rabbitmq/

**Comment by jamesgeddes** [comment]
https://simpleisbetterthancomplex.com/tutorial/2017/08/20/how-to-use-celery-with-django.html

**Comment by jamesgeddes** [comment]
Very Academy
* [Learn Django Celery with RabbitMQ - Install and create new celery instance, Run a simple task Part 1](https://youtu.be/fBfzE0yk97k)
* [Learn Django Celery - Sending Emails with Django and Celery - Part-2](https://www.youtube.com/watch?v=7dUxyIp5mMI)

**Comment by jamesgeddes** [comment]
Changed to from email of `support@geek.zone` as this allows recipients to reply.

**Comment by jamesgeddes** [comment]
Task `task_send_email` now available in `tasks.py` and awaiting PR.

**Comment by jamesgeddes** [comment]
@giulio-giunta Shall we discuss how to implement the infra for the workers cluster and the RabbitMQ server to ensure that nothing gets missed? Do [select a time](https://calendly.com/geekzone-james/30min) that's best for you.

**Comment by giulio-giunta** [comment]
Hi James,
I booked a meeting with you tomorrow at 10. If that's not viable for you,
we can reschedule whenever it's best for you.
Thanks.
Giulio

**Comment by jamesgeddes** [comment]
That's perfect @giulio-giunta thanks mate :smile:
