### ISSUE TITLE
Pre-Live Checklist

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#15]
## Background

Before we go live we should ensure we are doing everything we can to keep this application secure and performant. Django has provided a nice checklist that we should follow which can be found at https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/.

We should also ensure we follow the Stripe integration checklist before taking payments from real Geek.Zone members. The Stripe checklist can be found at https://stripe.com/docs/payments/checkout/live.

And finally we should ensure all requests and assets are served over HTTPS, and that certificate renewal is automated, or documented and delegated to a trusted individual.

**Comment by jamesgeddes** [comment]
Moved to 

https://github.com/GeekZoneHQ/web/wiki/Pre-live-checklist
