### ISSUE TITLE
Setup postgres database in AWS

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#17]
## Background

We have chosen to use PostgreSQL as our database for this project. We will need to set up a pgsql database in AWS before we go live - and ideally early on in the development process.

## Notes on approach

Two ways of deployment immediately come to mind:
* Use Amazon RDS
* Deploy to the kubernetes cluster

I would lean towards RDS for two reasons:
* It is a managed service that amazon secures, patches, and updates
* I believe it has high availability built in (fail over replication etc)
* I imagine that setting up a database in RDS would be rather tricky

Kubernetes does have some positives that come to mind though:
* We can install whatever extensions we want
* We can use whatever configuration we want
* If we moved to a different cloud provider the k8s configuration would likely require minimal changes

From a security, reliability, and performance perspective I believe it would be better to have a separate development and live database instance. 

### Impact

?

### Urgency

?

**Comment by CarwynNelson** [comment]
Bringing this further up the priority list as mentioned in #16 to aid in releasing #19.

For now we will go with a basic hand rolled AWS RDS Postgres database, and we can investigate further at a later time. At a minimum we should automate the deployment and management of the database via something like Cloudformation before we take it to production.

**Comment by CarwynNelson** [comment]
I have created a free-tier postgres database for the purpose of prototyping with. I have the username and password anyone needs it.

At the moment it is publicly accessible to make setup easier, but soon I will make it private to our VPC(s) and access will require a jump box.

**Comment by SamWinterhalder** [comment]
@giulio-giunta

**Comment by giulio-giunta** [comment]
The Terraform configuration to add a managed Postgres database is already in place for deploying both to AWS and Azure.
