### ISSUE TITLE
Code style and linting tools

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#175]
Now that we are growing in numbers we could do with some basic code style and linting tools for:
* Python
* HTML
* Javascript

Ideally this should run on a PR build in the CI system, but not run against the main branch as experience tells me that can be problematic.

**Comment by jamesgeddes** [comment]
@CarwynNelson Flake8 appears to be highly recommended for python, what do you think?

https://circleci.com/developer/orbs/orb/wearefair/flake8-orb

Will look into linters for front end

**Comment by jamesgeddes** [comment]
While we are at it, could include something like

https://pyup.io/safety/

**Comment by jamesgeddes** [comment]
[pipelinecomponents](https://hub.docker.com/u/pipelinecomponents) seem to have lots of really useful images

**Comment by jamesgeddes** [comment]
HTML validator https://hub.docker.com/r/cyb3rjak3/html5validator

**Comment by jamesgeddes** [comment]
many https://hub.docker.com/r/danielruthardt/linters

**Comment by jamesgeddes** [comment]
[Black](https://pypi.org/project/black/) appears to be the best way to get Python sorted automatically. Why warn when one can rectify?

**Comment by cooperlees** [comment]
> [Black](https://pypi.org/project/black/) appears to be the best way to get Python sorted automatically. Why warn when one can rectify?
> 
> https://circleci.com/developer/orbs/orb/dialogue/python#jobs-black

Black only auto formats. No linting or any other checking is performed. Black compliments flake8, isort, mypy etc.

**Comment by jamesgeddes** [comment]
@cooperlees thanks for clarifying, much appreciated.

We intend to use Black as part of our CI so will use the other tools mentioned.

**Comment by jamesgeddes** [comment]
Looks like [superlinter](https://github.com/github/super-linter) should be pretty good. Have updated the CircleCI file to include black, pylama and isort, and superlinter can handle everything else.
