### ISSUE TITLE
Payments for Membership

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#18]
> Requires further discussion and involvement from the Treasury and Trustees.

## Background

There are two tiers of membership planned
* Sand - basic annual membership at a cost of £1 + donation per year
* Space - monthly membership that gives you access to https://geek.zone/01. Expected to cost £1 + donation per month

We need to implement Sand membership before the release of membership management as that is what all existing Geek.Zone members are currently paying.

We are planning to support multiple methods for payment so as to be as inclusive as possible. The first payment method we plan to support is UK Direct Debit via BACS.

**Comment by jamesgeddes** [comment]
Thinking about this further, the reason why we need to ensure that "Space" membership must be part of "Sand" membership is downgrades. One can choose to be a Space member for just the one month that you need access to the Geek.Zone. You could then downgrade back to "Sand" and lose access to the space, but will still be able to come to public GZ events.

If we were to say that Space membership is a separate membership band, then the member would leave GZ when the month ended. This would currently be unconstitutional, so "Space" membership cannot be part of the membership of Geek.Zone as a CIO.

Effectively, though it is referred to as "membership", "Space Membership" is not a membership band. It is Geek.Zone selling access to Geek.Zone/01 (and every other Geek.Zone physical space) for £1 a one month period, and encouraging the individual to provide a donation.

If one wanted to access the Geek.Zone spaces for 3 months, the minimum one would pay is as follows.
- 12 Jan: £1 org membership fee, £1 space access fee
- 12 Feb: £1 space access fee
- 12 Mar: £1 space access fee
- 12 Apr: £0 - but you can still come to events until 12 Jan

I hope this makes sence and I've not made it sound super complicated!

**Comment by CarwynNelson** [comment]
> I hope this makes sence and I've not made it sound super complicated!

I think this helps. My initial thoughts are that we could "easily" handle this by having the member have two subscriptions running in Stripe at the same time.

eg:
* They sign up for Geek.Zone and start a "Sand Membership" subscription costing £1 + donation per annum
* They sign up for Space access and start  "Space Membership" subscription costing £1 per month + donation
* They can cancel the space membership at any time and that won't impact the sand membership

The caveat here is that we would have to ensure our system cancels both subscriptions if the member chooses to leave Geek.Zone entirely, but I don't think that's a big deal at all.

In fact I think this is a better way of handling it as it makes it clearer to members how they are being billed, and they can manage each subscription separately within their portal.

**Comment by jamesgeddes** [comment]
Ignorant n00b question: would two subscriptions mean that the user would be billed on two separate direct debits, our would they be bundled into the same one? Also, as long as we are showing an itemised list in the users Geek.Zone account, will the stripe setup make a difference to the user?

**Comment by jamesgeddes** [comment]
Could we ask the user to [set up a Direct Debit](https://stripe.com/docs/payments/bacs-debit/save-bank-details) payment method, then get them to pay their initial fee using it? Looks like this allows us to set amounts later.

**Comment by CarwynNelson** [comment]
> would two subscriptions mean that the user would be billed on two separate direct debits, our would they be bundled into the same one?

I'm fairly certain it would come out of the same direct debit, but I don't know if they would be charged twice. I think that would require some testing and research on our end - or at least asking Stripe support if they know.

> as long as we are showing an itemised list in the users Geek.Zone account, will the stripe setup make a difference to the user?

Probably not. On that note I've just noticed that a subscription can contain multiple line items, so we could model the subscription as two line items - one for the £1 minimum, and another for the donation.
The caveat is that a subscription can only contain line items with the same interval (monthly, yearly etc) so unfortunately we can't combine monthly and yearly charges inside of the same subscription. I can show you this in the dashboard if this doesn't make sense.

> Could we ask the user to set up a Direct Debit payment method, then get them to pay their initial fee using it? Looks like this allows us to set amounts later.

Yep this is how my current test implementation works. Once we have the direct debit payment method on file I believe you can set up further subscriptions / pricing and just tell stripe to use the existing / preferred payment method (or allow the user to select one if you have multiple on file).

**Comment by jamesgeddes** [comment]
Need to give user the opportunity to cancel at every step
