### ISSUE TITLE
Create Payments table

### ISSUE THREAD

**Issue by SamWinterhalder** [GeekZoneHQ/web#197]
Create a payments table to hold all successful payments

**Comment by SamWinterhalder** [comment]
@CarwynNelson The ERD says that the payments table should include `total_gbx`. Is this something we want right now or is storing `stripe_subscription_id` sufficient?

**Comment by CarwynNelson** [comment]
> @CarwynNelson The ERD says that the payments table should include `total_gbx`. Is this something we want right now or is storing `stripe_subscription_id` sufficient?

I think `stripe_subscription_id` should be sufficient for now.
