### ISSUE TITLE
Allow pull request deployments

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#21]
## Background

Currently all merges to master are automatically deployed to `test.geek.zone` using our circleci build. This is very useful - it allows anyone with commit access to get changes released without direct access to the Kubernetes cluster.

It would be great if we could deploy pull requests to the k8s cluster to allow for easier testing and review of pull requests. Right now this is possible if you have commit access as you can directly modify the circleci config and it will be run. The downside to this is that it deploys to `test.geek.zone`, removing what was there before.

I propose that we deploy all pull requests to a url like `pr-number-branch-name.pr.geek.zone` and then deploy to `test.geek.zone` on merge to master.

When we deploy this change to live merges to master would deploy to the home of this project instead of `test.geek.zone`.

Thoughts?

### Impact

?

### Urgency

?

**Comment by jamesgeddes** [comment]
Sounds good to me!

**Comment by jamesgeddes** [comment]
This was done
