### ISSUE TITLE
Accounts for those Under 18 Years of Age

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#22]
While anyone can be a Geek.Zone member regardless of their age, those under 18 years need oversight from their parent/guardian.

For MVP, only allow registration from those who are over 18 years old. Ask those under 18 to contact trustees@geek.zone

> Thanks for your interest in joining Geek.Zone! We are eager to have you on board, however, as you are under 18 we need to speak to your parent or guardian. Please ask them to email trustees@geek.zone to request membership on your behalf. Thanks!

**Comment by jamesgeddes** [comment]
Getting all set up on Ubuntu today, intend to get on this tomorrow XD
