### ISSUE TITLE
Setup SSL for join.geek.zone

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#256]
Relates to #12 

Use cloudflare to set up SSL for join.geek.zone. 

Can [terraform](https://registry.terraform.io/providers/cloudflare/cloudflare/latest) do this? Would be preferable to keep this in code if possible.

**Comment by giulio-giunta** [comment]
SSL has already been implemented for test.geek.zone, but once we switch to join.geek.zone, the same configuration will apply seamlessly.
TLS terminates at the load balancer.
