### ISSUE TITLE
Footer notices

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#265]
### Ideal
Add a footer to every page. Have it include the following text.

> The Geek.Zone membership system is currently in beta. Please email your feedback to dev@geek.zone so that we can improve it!

### Fast
Alternatively, add that text to the top of the member details page only.

**Comment by jamesgeddes** [comment]
As discussed in today's Dev meet please also add the following text to the footer.

> We do use some functional cookies to deliver functionality to you. Don't worry, we won't spy on you!

**Comment by tbentham** [comment]
Renamed since there's already a 'Footer' ticket at #191.
