### ISSUE TITLE
Update CircleCI config

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#271]
CircleCI needs rabbitmq and celery. Update.

**Comment by jamesgeddes** [comment]
I think we need this?

https://circleci.com/docs/2.0/custom-images/#circleci-dockerfile-wizard

**Comment by jamesgeddes** [comment]
As I understand it, I think we need to build a [custom docker image](https://circleci.com/docs/2.0/custom-images/#circleci-dockerfile-wizard) from the [CircleCI base image](https://hub.docker.com/r/cimg/base) that then adds in [Python](https://hub.docker.com/r/cimg/python) and [RabbitMQ](https://hub.docker.com/_/rabbitmq). Celery should come with `requirements.txt` and we can run a celery worker as part of the run commands.

@giulio-giunta Does that sound about right?

**Comment by giulio-giunta** [comment]
Hi James,
I'll look into it, but don't know if I'll manage to finish by 7pm tomorrow.

**Comment by jamesgeddes** [comment]
Perhaps it is better to start from the CircleCI base image then just [install stuff on it](https://stackoverflow.com/a/39627388/4162689).

**Comment by jamesgeddes** [comment]
@giulio-giunta Is this helpful?

[CI pipelines for testing microservices with DeployHub and CircleCI](https://circleci.com/blog/ci-pipelines-for-testing-microservices/)

**Comment by jamesgeddes** [comment]
...or this?

[Get an out-of-the-box solution for the most important services in your pipeline](https://circleci.com/blog/get-an-out-of-the-box-solution-for-the-most-important-services-in-your-pipeline/)
