### ISSUE TITLE
Remove profile image

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#276]
Remove all instances of profile image/selfie as this is not an MVP priority

**Comment by tbentham** [comment]
@jamesgeddes Should be solved with #272 as mentioned above, though let me know if I've missed something.

**Comment by jamesgeddes** [comment]
@tbentham Have you removed the python side of things too?

**Comment by jamesgeddes** [comment]
As long as it works and profile image is not visible to the user right now, I'm happy

**Comment by tbentham** [comment]
> @tbentham Have you removed the python side of things too?

As much as I could, though I left the migration files alone - I'm not sure if they need editing.

The form still seems to work fine anyway.

**Comment by jamesgeddes** [comment]
Perfect. A very elegant solution particularly considering that we will want to reinstate it post-MVP.

**Comment by jamesgeddes** [comment]
Thanks very much @tbentham
