### ISSUE TITLE
Rework force member payment

### ISSUE THREAD

**Issue by SamWinterhalder** [GeekZoneHQ/web#282]
The current method of forcing a member to payment, is **OK** for MVP but is not ideal.

The Stripe event being used for updating the payment status, to determine whether the user has started paying, is `payment_intent.created` but will come after `checkout.session.completed`. This means that once the user has finished the checkout session, it is not guaranteed that the user will be able redirected to membership settings, or access any page other than `confirm`.

A fix for this would be to either store when the member has completed checkout (`checkout.session.completed`) as the intial payment step instead of `payment_intent.created`, or request the payment status from Stripe. My preference is the first option.

**Comment by SamWinterhalder** [comment]
It should also be added to the docs that the Stripe listener needs to be running so that the payment status can be updated in the DB. If not, the user will not be able to view other pages as the member is not paying.

**Comment by Freshrojek** [comment]
The first option sounds good, but is there any way where `checkout.session.completed` could be true but the payment fails?

**Comment by SamWinterhalder** [comment]
Yes, but the problem is that a payment is not instant. When a member pays, it may take a few hours or even days for that payment to complete (and succeed), so we can't just force a member into payment if they have not paid. What I was trying to do was work out if a member is currently *paying* for their membership so I used `payment_intent.created` but on reflection it would probably be better to use `checkout.session.completed`.

**Comment by Freshrojek** [comment]
Ah okay, should we log another ticket to check after `checkout.session.completed` if the payment eventually fails or not? Actually, would this be a stripe/banks issue?

**Comment by SamWinterhalder** [comment]
These things are checked in `payments.py` when the event happens.

For example:
When we receive `invoice.paid` for the member, we would update the payment status, give them the `has_paid_sand` Django permission, log the payment in the DB, etc.
