### ISSUE TITLE
Fix Check Stripe payment

### ISSUE THREAD

**Issue by Freshrojek** [GeekZoneHQ/web#287]
https://www.loom.com/share/e20c574686194f368eb04f5f51636bfa

At the moment, whenever accessing `membership_details.html` or `membership_settings.html` it always asks to set up your direct debit again, because it hasn't received confirmation from stripe yet. Also in `register` view, it doesn't make it past the two lines `exec_time` `task_payment_check` to send a welcome email or render a new page. So after you register currently you have to head over to the login page as the current page doesn't change

**Comment by SamWinterhalder** [comment]
Hmm, I thought this was fixed in recent PR. Shall investigate tomorrow 🕵️

**Comment by SamWinterhalder** [comment]
@Freshrojek Was the Stripe listener being run when testing?

**Comment by jamesgeddes** [comment]
I feel that this is a PGL issue as it makes the user feel that their payment failed.

**Comment by SamWinterhalder** [comment]
@jamesgeddes Tested earlier, when meeting with Giulio, and I could not replicate the issue - seems to work fine locally so will need test.geek.zone to go live for testing.

**Comment by Freshrojek** [comment]
Hmm, let me reinstall the stripe listener maybe I've got a local problem

**Comment by jamesgeddes** [comment]
@SamWinterhalder will review this on the feature branch

**Comment by SamWinterhalder** [comment]
I can not replicate so shall close for now :)
