### ISSUE TITLE
Improvements to account creation

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#30]
* Password strength checking
* Throttling of login attempts

**Comment by jamesgeddes** [comment]
Is [django-password-strength](https://pypi.org/project/django-password-strength/) of any use? 

Also, (future improvement) this would be a great place to include the Geek.Zone affiliate link to LastPass

**Comment by jamesgeddes** [comment]
I'd argue that password length is more important than complexity, see

- [XKCD](https://xkcd.com/936/)
- [UK NCSC](https://www.ncsc.gov.uk/collection/passwords/updating-your-approach#PasswordGuidance:UpdatingYourApproach-Donotusecomplexityrequirements:~:text=Do%20not%20use%20complexity%20requirements)

I do agree that login throttling, 3 login attempts every minute for example, is a good idea.

**Comment by jamesgeddes** [comment]
Would recaptcha be a better first step than blindly throttling? I've created keys for geek.zone, where should I put them?

**Comment by jamesgeddes** [comment]
Split to #43

**Comment by jamesgeddes** [comment]
@CarwynNelson and I have agreed that we will change the password length to 9 but then have a password strength indicator that only goes fully green after 16 characters.
