### ISSUE TITLE
Prod build & deploy pipeline

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#329]
Create a CircleCI pipeline with the following steps (roughly)

- when a new PR is merged, rebuild the /web image and its dependencies
- publish image on https://hub.docker.com/u/geekzone
- Once new image is available, begin a [canary deployment](https://youtu.be/FT2O-qLj9Hc) of the new image.
- Automatically test blue env before each deployment ramp up step.
- If all tests pass, deploy new image to main production infra.

**Comment by jamesgeddes** [comment]
@kbcbals & @giulio-giunta One for you guys?

**Comment by giulio-giunta** [comment]
Yes, I can look after it.
Today I started watching some videos on circleci

**Comment by jamesgeddes** [comment]
Remember to let @kbcbals have some fun too :laughing:

**Comment by giulio-giunta** [comment]
I will

**Comment by giulio-giunta** [comment]
How can I reach him?

**Comment by jamesgeddes** [comment]
By @ mentioning him as I already have :laughing:

**Comment by kbcbals** [comment]
@giulio-giunta thanks Julio.
I can be reached @07714282347
kbcbala@gmail.com.
I did some basic learning about circle ci and integration with docker compose and eventually AWS.
Still trying to get grips together.
It would be nice if we can have a discussion to share

**Comment by giulio-giunta** [comment]
Sure, can I call you later on?

**Comment by giulio-giunta** [comment]
@kbcbals Sure, can I call you later on?

**Comment by kbcbals** [comment]
Thanks Giulio. Shopping for my daughter at the moment. Do you have a
preferred time.
 Cheers.

**Comment by giulio-giunta** [comment]
I'll have a break from 7:15 to 8:10pm

**Comment by kbcbals** [comment]
Fab. Cheers

**Comment by jamesgeddes** [comment]
@giulio-giunta are we canary testing or does that need to be logged separately?

**Comment by giulio-giunta** [comment]
@James Geddes ***@***.***> It does rolling deployment, not canary
deployment.

**Comment by kbcbals** [comment]
May be we need to create another issue for canary testing

**Comment by jamesgeddes** [comment]
Are we getting data back from the new instances to ensure that the new instances are succeeding?

**Comment by kbcbals** [comment]
Basically the pipeline stops after deployment. No confirmation as to
success or failure.
Giulio might confirm that.

Do you have any suggestion James?

**Comment by jamesgeddes** [comment]
I would like us to canary so that we can the data needed to roll forward or back. It is not a blocker to release. I will log a ticket.
