### ISSUE TITLE
On-demand test env

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#330]
Build a CircleCI pipeline that spins up a small copy of prod infra whenever a new ready-for-review PR is opened by a Geek.Zone GitHub Org member. Instance should be accessible at

https://pr[pr-number]-[repo-name]-test.geek.zone

Infra must be destroyed when PR is closed.

### Impact

High

### Urgency

Now

**Comment by jamesgeddes** [comment]
@kbcbals and @giulio-giunta One for you guys?

**Comment by kbcbals** [comment]
I can pickup this one.

**Comment by jamesgeddes** [comment]
Would be good to have the env spin up for 1 hour and then allow testers to manually redeploy for 1 hour with a comment in the PR.

**Comment by kbcbals** [comment]
@giulio-giunta one quick question, in the prod, are the kubernetes resources created by TF or Kubernetes?

**Comment by giulio-giunta** [comment]
Hi Bala,

It depends on the resources, some are created by Terraform others by
Kubernetes.
What resources do you refer to specifically?

**Comment by kbcbals** [comment]
I see that aws components like vpc,eks are modules in TF and kubernetes  as
a provider , in the infra repo

The reason I'm asking , the resources created TF will be deleted by TF.

What happens some objects like kubernetes namespaces are created by
manifest ? TF cant delete them.

Is it the case .

Cheers

**Comment by giulio-giunta** [comment]
You can create k8s namespace with Terraform as well, but atm this is not
implemented, so if you need to delete a namespace you need to do so by
using kubectl

**Comment by kbcbals** [comment]
I could create the k8s namespace using TF.

I could not pass the name of the the namespace on to it.

Also the 'delete' option in TF 'kubernetes_namespace' don't work as it
should be.
Do you have any suggestions on passing the ns name to TF.
I have checked env variables as well.

**Comment by giulio-giunta** [comment]
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace

If you want we can have a short meeting later on

**Comment by kbcbals** [comment]
Thanks. 8.30pm ? Or can you suggest after that

**Comment by jamesgeddes** [comment]
IMO we should aim toward everything-as-code, so TF everywhere it can.

**Comment by kbcbals** [comment]
I think that should be our final destination.

We should be using TF provider and modules to move the resources created by
k8s manifests on to TF

**Comment by jamesgeddes** [comment]
Agreed; 

1. make it work
2. make it work well
3. make it pretty

**Comment by kbcbals** [comment]
Yes. Its challenging. I know that.
Should be possible I think.
It would be neat and pretty once we do it.

**Comment by giulio-giunta** [comment]
I'm sorry Bala, I didn't see your message yesterday. If you want we can do
same time today

**Comment by kbcbals** [comment]
Np Giulio. We shall. Thanks

**Comment by giulio-giunta** [comment]
👍

**Comment by kbcbals** [comment]
Would 8.30pm suit you? Or can you suggest after that.

**Comment by jamesgeddes** [comment]
@kbcbals @giulio-giunta Is this done?

**Comment by giulio-giunta** [comment]
@James Geddes ***@***.***> Yes it is.
