### ISSUE TITLE
Gracefully handle existing email on registration

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#34]
![image](https://user-images.githubusercontent.com/3310215/89648048-84b01080-d8b6-11ea-813c-9c2ce9306fcf.png)

**Comment by jamesgeddes** [comment]
What are your thoughts on a combined login/register box? Is that possible?

**Comment by jamesgeddes** [comment]
must reject re-registration
should return error message "Looks like you already registered, please log in" and direct member to login page. requires #39

**Comment by jamesgeddes** [comment]
Done pending PR
