### ISSUE TITLE
No decimal values accepted as donation amounts

### ISSUE THREAD

**Issue by giulio-giunta** [GeekZoneHQ/web#364]
Currently when registering through test.geek.zone/memberships/register the system does not allow to insert decimal amounts as a donation. This causes the site to return a code 500 error
![image](https://user-images.githubusercontent.com/56529931/126069129-c3c42fa8-65d4-430a-a6d0-781338efa2eb.png)

### Impact

High

### Urgency

Now

**Comment by SamWinterhalder** [comment]
Correct me if I am wrong, but is it PGL to fix this or could we limit the member to integer donations and make decimals P1?
@Freshrojek

**Comment by giulio-giunta** [comment]
Hey guys,

I think James mentioned he'd want to manage donations in GBX.

If this complicates things a lot, for the time being I guess limiting
members to integer donations would be the best approach, as this would
prevent any error 500 response codes. Also, I think people would make
integer donations anyway.

On the other hand, if it's possible to change the code easily and
accept donations as decimal amounts, then the work would be done once for
ever.

Giulio

**Comment by opheliah95** [comment]
Hey all,

I think if we are going to make it into a integer donation, it may be a bit more natural if we set donations to a drop-down tiers, like £5, £20 etc. So rather than enter a number, members can choose a number from the drop down?  If it sounds complicated, we can drop this idea.

But I agree that we should look into the code and see if it can be easily fixed.

Ophelia

**Comment by Freshrojek** [comment]
Yeah I guess for now we need to make it only accept integers while we have a look at the decimals, but I don't think it's necessarily pgl but something that should be done sooner because James did want it done.

**Comment by SamWinterhalder** [comment]
Have found on line 160 of `memberships/views.py` we take the integer value of `donation` and create a total so this throws an error when supplied float.

`total = 1 if not donation else int(donation) + 1`

Unless people can see any reason not to, this will be made a float and rounded to 2 d.p. so requests made with `x` d.p. are rounded.

**Comment by Freshrojek** [comment]
Yeah we have rounded both `donation` and `total` to 2 decimal points in float, does this mean it is in GBX @giulio-giunta ?

**Comment by jamesgeddes** [comment]
@Freshrojek @SamWinterhalder @opheliah95 How are we getting on with this?

**Comment by Freshrojek** [comment]
> @Freshrojek @SamWinterhalder @opheliah95 How are we getting on with this?

Last time I spoke to @SamWinterhalder, we needed to wait for logging.geek.zone to come online before trying the proper way

**Comment by giulio-giunta** [comment]
Hi guys,

The issue with logs filling up the volume is now solved. Btw, even with
that, logs could be retrieved directly from Kubernetes anyway.

Giulio

**Comment by Freshrojek** [comment]
Trying to progress on this but can't run the project locally as I'm fighting with `psycopg2` errors >:(

**Comment by Freshrojek** [comment]
PR #576 Closed this
