### ISSUE TITLE
Duplicate Email salutation

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#391]
![Screenshot_20211015-113351.jpg](https://user-images.githubusercontent.com/14872636/137474175-805c3702-2032-4428-b4ea-42d972666d6a.jpg)

Email says hi name and hello name

### Impact

High

### Urgency

Now

**Comment by Freshrojek** [comment]
Hi @K95Monty 👋🏼 
Are you working on this currently?

**Comment by SamWinterhalder** [comment]
If I recall correctly, this was because both the Django template and email contents contain greetings.

**Comment by Freshrojek** [comment]
Hey Sam, yeah we've just got to remove either `Hi {{user}}!` from `welcome_email.html` or `Hello {{name|safe}}!` from `email_message.html` I'm pretty sure
Was gonna make a pr for it but didn't want to takeover if @K95Monty wanted to do it as they're assigned 🤷🏼

**Comment by jamesgeddes** [comment]
@K95Monty and I have discussed this and Kathy is working on it 😄 

How are you getting on @K95Monty?

**Comment by Freshrojek** [comment]
Awesome! Happy to help if needed 🙂
