### ISSUE TITLE
Incorrect stripe handoff

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#392]
When returning from stripe after the initial direct debit setup, the user is sent to

https://test.geek.zone/memberships/confirm/

This asks them to set up their direct debit which they have just done.

Users should be sent to a page that thanks them for setting up their direct debit and directs them to complete their member details.

The user should be considered a member from the moment they set up their direct debit. If the direct debit subsequentially fails, the member should be told to set up a new direct debit.

### Impact

High

### Urgency

Now

**Comment by SamWinterhalder** [comment]
Just a little nudge in the right direction - I wasn't sure if it would work well enough (it appears not), but I essentially wrote to the database when the member has made payment and then in the redirect checked if this value in the database existed.

I think the most likely problem is that it does not write to the database, before the check is made in the redirect, it is just not quick enough. What made this hard for me was that there is no garuntee that the payment will be made, it can take up to 72 hours for a payment to go through, and it could not be successful at any time up to that point.

https://github.com/GeekZoneHQ/web/blob/a00d6657529dfc971a8499cbec3a1695a19f0fa9/memberships/views.py#L230-L233

**Comment by jamesgeddes** [comment]
@SamWinterhalder thanks muchly, very helpful.

@blackbird7958 If we can tell the user a bit more info then this will be less confusing for them.

**Comment by jamesgeddes** [comment]
Just to confirm, we have decided that the user should be considered a member from the moment they set up their direct debit. If the direct debit subsequentially fails, the member should be told to set up a new direct debit.

**Comment by Freshrojek** [comment]
Had a chat with @crouchingtigerhiddenadam earlier and we think we are gonna 🪓  the code mentioned above, because in `tasks.py` there's already a decent check for if a member doesn't have the right perms after a certain amount of time. So we think we are just going to edit that

**Comment by Freshrojek** [comment]
Hey 👋🏼  @crouchingtigerhiddenadam  how's this ticket going? Let me know if you need a hand or get bored of it or something lol
