### ISSUE TITLE
Implement reCAPTCHA v3

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#43]
Implement Google reCAPTCHA v3 to identify when a guest appears to be a bot, then challenge them if they might be a bot.

Split from #30

**Comment by jamesgeddes** [comment]
@sharif2315 Want to have a go at this?

**Comment by jamesgeddes** [comment]
We should put reCAPTCHA everywhere that we require user input as a minimum.

**Comment by jamesgeddes** [comment]
This is important for pre-go-live as we do not want to be overrun by bots! That said, most bots are not going to be happy to pay £1 to join... ...still, belt and braces is best.

**Comment by Freshrojek** [comment]
Had an issue with convincing google I'm a robot for a while, but worked when using Googlebot 2.0 and sending a lot of requests really fast in incognito. Currently now working on how to handle the error if the score is too low or the token is invalid

**Comment by jamesgeddes** [comment]
What is the progress on this @Freshrojek? Can we close this off?

**Comment by Freshrojek** [comment]
Yeah it's all done I believe

**Comment by jamesgeddes** [comment]
@Freshrojek what's the PR for this?

**Comment by jamesgeddes** [comment]
The PR for this #99?

**Comment by Freshrojek** [comment]
Yeah that's it!
