### ISSUE TITLE
Action "bug" and "junk" branches

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#432]
### What did you expect?

The `bug` branch type should be built in the CircleCI pipeline as normal, same as `feature`. 

All `junk` branches must not be built. We should block them from merging too.

Should follow [CONTRIBUTING](https://github.com/GeekZoneHQ/web/blob/master/CONTRIBUTING.md#naming) convention.

### What actually happened?

`bug` and `junk` branches are currently not handled.

### Impact

High

### Urgency

Now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giulio-giunta** [comment]
@jamesgeddes What pattern does the bug branch follow? Is it like feature, so **/bug-.*/** ?

**Comment by jamesgeddes** [comment]
Same format just with change in type name. I have updated the ticket description to better explain.

**Comment by giulio-giunta** [comment]
I noticed that the PR#450 didn't trigger a build since the build was allowed only from "master", "feature-.*" and "bug-.*" branches. I changed this so that now all branched will build apart from "junk-.*" and "doc-.*". 
Please let me know if this works.

**Comment by jamesgeddes** [comment]
sgtm - the types let us run different pipelines if needed
