### ISSUE TITLE
Check that "geekzone" is mentioned on member bank statements

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#434]
### What's your idea?

Many companies fail to make it perfectly clear who they are on their customer bank statement. This leads to confusion and inconvenience on the customer side.

Double check that any bills we send to our members clearly mention `geekzone` in some form.

### Impact

High

### Urgency

Now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Freshrojek** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/72669630/166146969-12d07b8a-71e1-40d7-af1f-6ba799489991.png">

**Comment by Freshrojek** [comment]
Here you can see in the Stripe email that Geek.Zone is stated twice, and the reference contains "GZ" in it which indicates where the payment is going. Due to this I think we can close it 👍🏼
