### ISSUE TITLE
Run Tailwind CSS in Docker

### ISSUE THREAD

**Issue by tbentham** [GeekZoneHQ/web#456]
### What's your idea?

Create a set-up for running Tailwind CSS in a Docker container

A work currently in progress, based on [tristanstraub/docker-tailwindcss](https://github.com/tristanstraub/docker-tailwindcss).

### Impact

Low

### Urgency

Now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by giulio-giunta** [comment]
Perfect! Thanks Tristan

**Comment by giulio-giunta** [comment]
Hey @tbentham, 

I ran the container with sudo privileges and it worked, but after a couple of minutes it got killed because of out of memory. 

I also run the build.sh script in the repo we cloned, and the behaviour was the same (an image was created, a container ran from that image, but shortly after the container got killed)

**Comment by tbentham** [comment]
If it's memory, then my first guess would be that the massive `styles.css` file that gets generated in `dist` is causing the crashes. Maybe try using `tailwind build` in place of `tailwind start`, and see what difference it makes?

Tailwind can also run in [just-in-time mode](https://tailwindcss.com/docs/just-in-time-mode), which means it creates the final, compressed build of `styles.css` during development and updates it on-the-fly. Might be worth switching to that if the larger CSS file is causing the problem.

**Comment by giulio-giunta** [comment]
Hi Tristan,

in build.sh I replaced `yarn tailwind build $TAILWIND/static_src/src/styles.css
-c $TAILWIND/static_src/tailwind.config.js -o $
TAILWIND/static/css/dist/styles.css` with

`yarn tailwind start $TAILWIND/static_src/src/styles.css -c
$TAILWIND/static_src/tailwind.config.js
-o $TAILWIND/static/css/dist/styles.css`

but I received this error:
tailwindcss v2.2.19

Invalid command: start

Usage:
   tailwindcss <command> [options]

Commands:
   init [options]

Options:
   -h, --help               Display usage information

error Command failed with exit code 1.

**Comment by giulio-giunta** [comment]
Hey Tristan, 
I added Tailwind in docker-compose, so to test it you need to clone the "feature-docker-tailwind" branch and run the following commands:

- docker-compose build tailwind
- docker-compose run tailwind
 
Once the shell opens inside the container (showing /usr/src/app $), you need to run 
- yarn tailwind build static_src/src/styles.css -c static_src/tailwind.config.js -o static/css/dist/styles.css

This container is able only to run "tailwind build". If you need to also run "tailwind start" or other commands, we need to work on  our backend image and add node.js, npm, yarn. It can be done, but that increases the size of the image.

Let me know if this works for you.
Thanks.

**Comment by giulio-giunta** [comment]
Hi Tristan, 
I created a new branch and PR #484 related to this issue. 
When you have time, could you review it, please?
Thanks.
Giulio
