### ISSUE TITLE
Basic user registration

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#6]
## Requirements
A basic user registration form that allows new people to sign up for Geek.Zone membership. This initial basic form should focus on the minimum required to register someone to Geek.Zone.

* full name
* preferred name
* email address
* date of birth (saved to the db in iso8601 format)
* a password (so they can log in to their account)
* Their agreement to the geek.zone constitution

This first pass does not include taking payments

**Comment by jamesgeddes** [comment]
added initial version to userform branch. need to go through and add correct field names but I should probably sleep.

**Comment by CarwynNelson** [comment]
pull request available at #7

**Comment by jamesgeddes** [comment]
@sharif2315 Is this something you might be interested in?

**Comment by sharif2315** [comment]
Hi James,

Yup, I'm happy to start on that

**Comment by CarwynNelson** [comment]
@sharif2315 Apologies for some late notice.

Myself and @jamesgeddes have had further discussion about this ticket on Discord and think that it would be best to simplify the registration form for new geek.zone members.

Current thinking is that the following information should be required for registration.
* full name
* preferred name
* email address
* date of birth (saved to the db in iso8601 format)
* a password (so they can log in to their account)
* Their agreement to the geek.zone constitution
* Their £1 membership fee plus any regular donation the new member wants to make

I think payments should be done in another issue to keep things simpler.

I'll update the main issue description to fit this. Does that seem reasonable?

**Comment by jamesgeddes** [comment]
@sharif2315 how are you getting on?
