### ISSUE TITLE
Add your name to humans.txt

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#60]
Geek.Zone is all about our members, so your contribution is important! Add your name to humans.txt

**Comment by profread** [comment]
Where is the humans.txt file can't locate it

**Comment by jamesgeddes** [comment]
@CarwynNelson moved it to the public root

https://github.com/GeekZoneHQ/web/blob/master/memberships/templates/memberships/humans.txt

**Comment by profread** [comment]
Will find it then

**Comment by jamesgeddes** [comment]
Closing this issue as we need to focus on [pre-go-live](https://github.com/GeekZoneHQ/web/issues?q=is%3Aissue+is%3Aopen+label%3Apre-go-live) issues.
