### ISSUE TITLE
Add first-timers-only badge

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#61]
Add the first-timers-only badge to the web repo readme

`[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)
`

**Comment by profread** [comment]
Submitted a PR to this issue

**Comment by jamesgeddes** [comment]
Closing this issue as we need to focus on [pre-go-live](https://github.com/GeekZoneHQ/web/issues?q=is%3Aissue+is%3Aopen+label%3Apre-go-live) issues.
