### ISSUE TITLE
Add links to first timer guide to readme

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#62]
In the "Contributing" section of readme.md add link to

- https://www.firsttimersonly.com/
- http://opensource.guide/how-to-contribute/

**Comment by sleekyom** [comment]
Hi james, can i take this up?

**Comment by jamesgeddes** [comment]
@sleekyom Looks like profread has already submitted a PR! Have you had a look at our other tickets? You seem to be above [first-timers-only](https://www.firsttimersonly.com/#are-you-an-oss-project-owner:~:text=Are%20you%20an%20OSS%20Project%20Owner%3F) anyway, so the [pre-go-live](https://github.com/GeekZoneHQ/web/issues?q=is%3Aissue+is%3Aopen+label%3Apre-go-live) tickets are our priority right now.

**Comment by sleekyom** [comment]
Yes, I will check that out right now

Thanks

**Comment by jamesgeddes** [comment]
Closing this issue as we need to focus on [pre-go-live](https://github.com/GeekZoneHQ/web/issues?q=is%3Aissue+is%3Aopen+label%3Apre-go-live) issues.
