### ISSUE TITLE
Write GitHub Sponsors Intro

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#64]
I have created a wiki page, [GitHub Sponsors Intro](https://github.com/GeekZoneHQ/web/wiki/GitHub-Sponsors-Intro), so that we can all contribute to this together!

I have signed GZ up for GitHub Sponsors. Before they can accept our application, they need;

**Short bio (250 characters)**
This is used where your sponsorship is shared (e.g., social cards and github.com/sponsors if you opt-in to be featured).

**Introduction** 
This is the main content that appears on the GeekZoneHQ GitHub Sponsors profile, so it is a great opportunity to help potential sponsors learn more about you, your work, and why their sponsorship is important to you.

Here are some ideas of what we can tell potential sponsors:
- Who are you, and where are you from?
- What are you working on?
- Why is their sponsorship important? How will you use the funds?

### Impact

?

### Urgency

?

**Comment by giulio-giunta** [comment]
[Short BIO.txt](https://github.com/GeekZoneHQ/web/files/5482727/Short.BIO.txt)

**Comment by jamesgeddes** [comment]
Done! Awaiting GitHub approval.
