### ISSUE TITLE
Add licence shield to readme.md

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#65]
[First timers only](https://www.firsttimersonly.com/) please!

Add this shield to the top of readme.md

https://img.shields.io/github/license/geekzonehq/web

If you would like to, I would be happy to go through this with you together. Just [select a time](https://calendly.com/geekzone-james/30min) that works best for you.

**Comment by profread** [comment]
I will like to can i go ahead please?

**Comment by jamesgeddes** [comment]
@profread you have already done a few first-timers-only tasks, leave some fun for others 😄 

Have you had a look at some of our other tickets?

**Comment by profread** [comment]
Alright, are there some doc issues to work on?

**Comment by sudh33ra** [comment]
@jamesgeddes may I please?

**Comment by jamesgeddes** [comment]
@sudh33ra looks like you are not a first timer, so leave some for others :smile: Have you had a look at any of our other issues?

**Comment by jamesgeddes** [comment]
@profread Everything is logged in our issues at the moment. Take your pick :smile:

**Comment by Fogeinator** [comment]
Haii, is this still open? It'd be my first :D

**Comment by jamesgeddes** [comment]
@Fogeinator 299 contributions in the last year! You are well beyond first-timers-only issues :smile: How about some of our other issues?

**Comment by jamesgeddes** [comment]
Closing this issue as we need to focus on [pre-go-live](https://github.com/GeekZoneHQ/web/issues?q=is%3Aissue+is%3Aopen+label%3Apre-go-live) issues.

**Comment by Fogeinator** [comment]
Hahaha I just contribute to my own repos, never tried to do anything beyond that 😅 but hope stuff gets done over at pre-go-live !!
