### ISSUE TITLE
adding my account to have access to Twilio

### ISSUE THREAD

**Issue by pradeeps** [GeekZoneHQ/web#651]
### What's your idea?

I would like to implement https://github.com/GeekZoneHQ/web/issues/50 which is blocking https://github.com/GeekZoneHQ/web/issues/628. I understand we already have a Twilio account which I can use. Can someone please add me or provide me access so I can get the keys?

### User Story

As a developer of GZ
I would like to have an account for Twilio
So that I can implement https://github.com/GeekZoneHQ/web/issues/50

### Impact

High

### Urgency

Now

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesgeddes** [comment]
I have set up an @geek.zone email address for you and have invited it to Twilio. Huzzah.
