### ISSUE TITLE
Change executor in cicd pipeline

### ISSUE THREAD

**Issue by giulio-giunta** [GeekZoneHQ/web#681]
### What did you expect?

We expect the cicd pipeline to succeed.

### What actually happened?

The executor used to run the cicd pipeline create a Geek Zone backend image with a Python version that does not reflect what's configured in the Dockerfile. 
As a consequence of this, Snyk fails the pipeline because it detects several vulnerabilities.

### Impact

High

### Urgency

Now

### Relevant log output

```shell
Tested 3 projects, 2 contained vulnerable paths.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesgeddes** [comment]
Resolved by #675
