### ISSUE TITLE
Verify email

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#85]
Allow user to click link in email to verify email ownership.

Email should show as _unverified_ in `member_details` until verification is complete

Emails should come from hq@geek.zone

**Comment by jamesgeddes** [comment]
Potential options
- https://pypi.org/project/django-email-verification/
- https://pypi.org/project/Django-Verify-Email/

**Comment by jamesgeddes** [comment]
Would be best to be able to call the verification at a point of our choosing which appears to be easier in django-email-verification

**Comment by jamesgeddes** [comment]
@Freshrojek #39 is now in master

**Comment by Freshrojek** [comment]
I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes  @CarwynNelson  have you guys got any tips? thanks in advance!

**Comment by Freshrojek** [comment]
> 
> 
> I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes @CarwynNelson have you guys got any tips? thanks in advance!

I'm getting 'User has no member' in line 157 of views.py:
        "form": MemberDetailsForm(instance=request.user.member),

**Comment by CarwynNelson** [comment]
> I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes  @CarwynNelson  have you guys got any tips? thanks in advance!
> 

There are a couple ways you could go about it.

There is a file in the project called something like db.sqlite which you can just delete and then run the migrate command.

Another way is to create a superuser account which you can then use to login to the admin panel and delete your user account.

https://djangocentral.com/creating-super-user-in-django/

And finally you could open the db.sqlite file in a sqlite database tool and delete stuff that way.

Personally I just create a superuser account and delete or modify stuff that way.

**Comment by CarwynNelson** [comment]
> > 
> > 
> > I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes @CarwynNelson have you guys got any tips? thanks in advance!
> 
> I'm getting 'User has no member' in line 157 of views.py:
>         "form": MemberDetailsForm(instance=request.user.member),
> 

How was this user created? A user will only have a member associated with it if it was created via the registration form, or at least via the Member.create method

**Comment by Freshrojek** [comment]
> 
> 
> > I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes  @CarwynNelson  have you guys got any tips? thanks in advance!
> 
> There are a couple ways you could go about it.
> 
> There is a file in the project called something like db.sqlite which you can just delete and then run the migrate command.
> 
> Another way is to create a superuser account which you can then use to login to the admin panel and delete your user account.
> 
> https://djangocentral.com/creating-super-user-in-django/
> 
> And finally you could open the db.sqlite file in a sqlite database tool and delete stuff that way.
> 
> Personally I just create a superuser account and delete or modify stuff that way.

Thanks Carwyn! Created a superuser now and deleted that way

**Comment by Freshrojek** [comment]
> 
> 
> > > I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes @CarwynNelson have you guys got any tips? thanks in advance!
> > 
> > 
> > I'm getting 'User has no member' in line 157 of views.py:
> > "form": MemberDetailsForm(instance=request.user.member),
> 
> How was this user created? A user will only have a member associated with it if it was created via the registration form, or at least via the Member.create method

I created it through the registration form

**Comment by CarwynNelson** [comment]
> > 
> > 
> > > > I'm having trouble, I need to log in in order to verify my email but I can't and can't create a new account with the same email, @jamesgeddes @CarwynNelson have you guys got any tips? thanks in advance!
> > > 
> > > 
> > > I'm getting 'User has no member' in line 157 of views.py:
> > > "form": MemberDetailsForm(instance=request.user.member),
> > 
> > How was this user created? A user will only have a member associated with it if it was created via the registration form, or at least via the Member.create method
> 
> I created it through the registration form
> 

Hmm.. that is very strange. I would probably have to see what you are doing to get a better idea of some further debugging steps

**Comment by jamesgeddes** [comment]
@Freshrojek Can you record a [loom](https://www.loom.com/)?

**Comment by Freshrojek** [comment]
Ahh as I was recording a loom, I found out the problem, I hadn't clicked the 'log out' button before I tried to log in - I forgot that once you sign up it has you already logged in.

**Comment by jamesgeddes** [comment]
@Freshrojek How are you getting on with this?

**Comment by Freshrojek** [comment]
> @Freshrojek How are you getting on with this
Tried to send a commit today but was in the library and uni WiFi is something else. Verify email will only work if the registration form is a modelForm and meets some confusing requirements that would mean changing our form, so I'm in the proceeds of creating our own verification function, I have made a code and been able to send it but just gotta verify it now

**Comment by jamesgeddes** [comment]
If you cannot get it to work on-demand, go with sending an email on the registration form. We can improve it later.

**Comment by Freshrojek** [comment]
With my last commit on the branch, I'm pretty sure it's all done! Sunday when I'm back on hopefully I'll be able to check and make a pull request.
