### ISSUE TITLE
Membership Renewal Date

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#88]
When a new member joins and their payment is received, set their renewal_datetime to now+one year. Requires #89.

Those who join on a 29 Feb renew on the following 1 Mar.

If member renews (when the next years payment clears), renewal_datetime=renewal_datetime+[one year]

Show renewal_datetime in member_details. Exclude from member_settings.

**Future consideration:**

While we need this available just for Sand membership at MVP, in the future every group will need it's own renewal date. See #47.

**Comment by jamesgeddes** [comment]
@carwynnelson do we have any handy dandy flags to say whether a member has paid?

**Comment by CarwynNelson** [comment]
> @carwynnelson do we have any handy dandy flags to say whether a member has paid?

Not at the moment, but stripe will send us a notification via webhook when they do and we could write that to the database to be queried at a later date.

**Comment by jamesgeddes** [comment]
Fabaroonie. I've logged #89.

**Comment by SamWinterhalder** [comment]
Too broad.

Broken down into smaller tickets.
