### ISSUE TITLE
Handy Dandy Payment Flag

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#89]
Provide a global flag to easily check whether a member has paid their Sand membership fee.

Could be a datetime to aid the calculation of #88

**Comment by jamesgeddes** [comment]
This might leave us with technical debt so @CarwynNelson and @SamWinterhalder we should probably discuss a bit further

**Comment by jamesgeddes** [comment]
Relates to #47

**Comment by SamWinterhalder** [comment]
Relates to #195
