### ISSUE TITLE
Production Kubernetes Cluster

### ISSUE THREAD

**Issue by CarwynNelson** [GeekZoneHQ/web#9]
## Background

I quickly created a kubernetes cluster in AWS using EKS so that we could have a reasonable testing environment whilst we build up the feature set for this project.

At some point we will need to spend some time creating a cluster that is ready for production. This new cluster should:
- [x] Have all of its configuration in a git repository
- [x] Follow available security guidance
- [x] Make use of Kubernetes concepts such a namespaces to separate out different GeekZone projects

It is likely that the configuration for this new cluster will have to be split out into its own repository, but as the cluster originated from this work it makes sense to initially track this issue here.

> We also need to be conscious of cost. The last time I tried to run up a Kubernetes cluster using EKS it ended up costing us ~$90 in a single month. This isn't a massive amount of money on its own but if left alone it could have easily taken out a big chunk of our AWS budget. Just something to be wary of

### Impact

?

### Urgency

?

**Comment by jamesgeddes** [comment]
Another one assigned to you that @giulio-giunta @Freshrojek and I are eager to learn about

**Comment by SamWinterhalder** [comment]
@giulio-giunta

**Comment by giulio-giunta** [comment]
The Terraform configuration to create Geek-Zone k8s cluster both in AWS and Azure is already in place. In both cases the cluster is deployed in private subnets and access is only granted to Geek.Zone dev members.
