### ISSUE TITLE
Improve styling (baseline)

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#96]
General style improvements. Dealers choice on design, as long as it adheres to modern style recommendations and GZ colours - #000000, #ff0000 and #ffff00.

**Comment by jamesgeddes** [comment]
Perhaps this is a bit much for one ticket. Feel free to split it out if you prefer @tbentham

**Comment by tbentham** [comment]
@jamesgeddes Is there an existing branch for this, or shall I make a new one?

**Comment by jamesgeddes** [comment]
A new branch would good :smile:

**Comment by jamesgeddes** [comment]
Split info buttons to #104

**Comment by jamesgeddes** [comment]
Split "Make log in page centralised" to #107

**Comment by jamesgeddes** [comment]
Split "Make initial registration page centralised" to #108

**Comment by tbentham** [comment]
> 
> 
> General style improvements. Dealers choice on design, as long as it adheres to modern style recommendations and GZ colours - #000000, #ff0000 and #ffff00.

How flexible is the colour scheme? (I ask because main.css currently uses #111111 and #fff000 for black and yellow.)

**Comment by jamesgeddes** [comment]
It would be nice if we could stick as close to our main colours as possible, but its not obligatory so dealers choice. The current CSS can basically be ignored as we have done basically nothing with it.

**Comment by tbentham** [comment]
Resolved by #150.
